language: node_js
node_js:
  - "12"
  - "10"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.8"
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mjtruog@gmail.com
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    template:
      - "%{repository_slug} (%{branch} - %{commit}) %{author}: %{commit_message}"
      - "View Changes %{compare_url}"
      - "Build #%{build_number}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
